@startuml
package mx.com.oitic.deportextil.orm  {

}
package mx.com.oitic.deportextil.dao  {

}
package mx.com.oitic.deportextil.dto  {

}


mx.com.oitic.deportextil.dao +-- mx.com.oitic.deportextil.orm
mx.com.oitic.deportextil.dao +-- mx.com.oitic.deportextil.dto


@enduml
